export const PERFUMES = [
  { name: "Baccarat Rouge 540", house: "Maison Francis Kurkdjian", rating: 4.9, emoji: "✦", notes: "Jasmine · Saffron · Amberwood" },
  { name: "Sauvage EDP", house: "Dior", rating: 4.7, emoji: "◈", notes: "Bergamot · Ambroxan · Pepper" },
  { name: "Black Orchid", house: "Tom Ford", rating: 4.8, emoji: "❋", notes: "Black Truffle · Ylang · Patchouli" },
  { name: "Aventus", house: "Creed", rating: 4.6, emoji: "⬡", notes: "Blackcurrant · Birch · Ambergris" },
  { name: "Oud Wood", house: "Tom Ford", rating: 4.8, emoji: "◉", notes: "Oud · Sandalwood · Rosewood" },
  { name: "La Vie Est Belle", house: "Lancôme", rating: 4.5, emoji: "✿", notes: "Iris · Gourmand · Vanilla" },
  { name: "Bleu de Chanel EDP", house: "Chanel", rating: 4.7, emoji: "◇", notes: "Citrus · Labdanum · Sandalwood" },
  { name: "Tobacco Vanille", house: "Tom Ford", rating: 4.7, emoji: "☽", notes: "Tobacco · Vanilla · Dried Fruit" },
  { name: "Acqua di Giò", house: "Armani", rating: 4.5, emoji: "〜", notes: "Sea Notes · Bergamot · Musk" },
  { name: "Flowerbomb", house: "Viktor & Rolf", rating: 4.5, emoji: "❀", notes: "Rose · Jasmine · Patchouli" },
  { name: "Good Girl", house: "Carolina Herrera", rating: 4.4, emoji: "◆", notes: "Jasmine · Cacao · Tuberose" },
  { name: "Olympéa", house: "Paco Rabanne", rating: 4.4, emoji: "○", notes: "Vanilla · White Tea · Cashmere Wood" },
  { name: "Alien", house: "Mugler", rating: 4.3, emoji: "✧", notes: "Jasmine · White Amber · Cashmeran" },
  { name: "Angel", house: "Mugler", rating: 4.2, emoji: "★", notes: "Chocolate · Patchouli · Caramel" },
  { name: "Coco Mademoiselle", house: "Chanel", rating: 4.6, emoji: "⊛", notes: "Orange · Rose · Patchouli" },
  { name: "Miss Dior", house: "Dior", rating: 4.5, emoji: "✾", notes: "Rose · Peony · Musk" },
  { name: "J'adore", house: "Dior", rating: 4.4, emoji: "⊕", notes: "Ylang · Rose · Jasmine" },
  { name: "Light Blue", house: "Dolce & Gabbana", rating: 4.3, emoji: "≋", notes: "Sicilian Lemon · Apple · Cedar" },
  { name: "Daisy", house: "Marc Jacobs", rating: 4.2, emoji: "❁", notes: "Violet · Strawberry · Jasmine" },
  { name: "Si", house: "Armani", rating: 4.4, emoji: "⊙", notes: "Blackcurrant · Rose · Vanilla" },
  { name: "Chanel No. 5", house: "Chanel", rating: 4.6, emoji: "⑤", notes: "Aldehyde · Rose · Sandalwood" },
  { name: "Chance Eau Tendre", house: "Chanel", rating: 4.5, emoji: "☘", notes: "Grapefruit · Jasmine · White Musk" },
  { name: "N°19", house: "Chanel", rating: 4.3, emoji: "⊞", notes: "Iris · Neroli · Vetiver" },
  { name: "Shalimar", house: "Guerlain", rating: 4.4, emoji: "◎", notes: "Bergamot · Vanilla · Opoponax" },
  { name: "Mon Guerlain", house: "Guerlain", rating: 4.3, emoji: "♦", notes: "Lavender · Vanilla · Sandalwood" },
  { name: "La Petite Robe Noire", house: "Guerlain", rating: 4.2, emoji: "✂", notes: "Cherry · Rose · Patchouli" },
  { name: "Idôle", house: "Lancôme", rating: 4.2, emoji: "⊱", notes: "Rose · Jasmine · Musk" },
  { name: "Trésor", house: "Lancôme", rating: 4.3, emoji: "◈", notes: "Apricot · Rose · Iris" },
  { name: "Miracle", house: "Lancôme", rating: 4.1, emoji: "✺", notes: "Lychee · Magnolia · Amber" },
  { name: "Boss Bottled", house: "Hugo Boss", rating: 4.3, emoji: "⊡", notes: "Apple · Cinnamon · Sandalwood" },
  { name: "Hugo Man", house: "Hugo Boss", rating: 4.0, emoji: "◰", notes: "Apple · Oakmoss · Pine" },
  { name: "1 Million", house: "Paco Rabanne", rating: 4.4, emoji: "①", notes: "Grapefruit · Cinnamon · Leather" },
  { name: "Invictus", house: "Paco Rabanne", rating: 4.4, emoji: "⊳", notes: "Grapefruit · Marine · Guaiac Wood" },
  { name: "Guilty", house: "Gucci", rating: 4.2, emoji: "⊗", notes: "Pink Pepper · Lilac · Amber" },
  { name: "Bloom", house: "Gucci", rating: 4.3, emoji: "⚘", notes: "Tuberose · Jasmine · Rangoon Creeper" },
  { name: "The One", house: "Dolce & Gabbana", rating: 4.4, emoji: "❶", notes: "Tobacco · Amber · Ginger" },
  { name: "Pour Homme", house: "Dolce & Gabbana", rating: 4.2, emoji: "◑", notes: "Lavender · Tobacco · Amber" },
  { name: "Eros", house: "Versace", rating: 4.3, emoji: "⊚", notes: "Mint · Green Apple · Vanilla" },
  { name: "Dylan Blue", house: "Versace", rating: 4.2, emoji: "◐", notes: "Fig · Violet · Musk" },
  { name: "Bright Crystal", house: "Versace", rating: 4.2, emoji: "◭", notes: "Pomegranate · Yuzu · Lotus" },
  { name: "Armani Code", house: "Armani", rating: 4.3, emoji: "⊠", notes: "Bergamot · Guaiac Wood · Tonka" },
  { name: "Stronger With You", house: "Armani", rating: 4.4, emoji: "⊹", notes: "Pink Pepper · Sage · Vanilla" },
  { name: "Y EDP", house: "Yves Saint Laurent", rating: 4.4, emoji: "⊻", notes: "Bergamot · Ginger · Fir Balsam" },
  { name: "Black Opium", house: "Yves Saint Laurent", rating: 4.5, emoji: "☕", notes: "Coffee · Vanilla · White Flowers" },
  { name: "Libre", house: "Yves Saint Laurent", rating: 4.4, emoji: "⊼", notes: "Lavender · Mandarin · Musk" },
  { name: "Mon Paris", house: "Yves Saint Laurent", rating: 4.3, emoji: "⊽", notes: "Strawberry · Peony · White Musk" },
  { name: "L'Homme", house: "Yves Saint Laurent", rating: 4.3, emoji: "⋈", notes: "Ginger · Basil · White Cedar" },
  { name: "Spicebomb", house: "Viktor & Rolf", rating: 4.4, emoji: "⋉", notes: "Cayenne · Cinnamon · Leather" },
  { name: "Spicebomb Infrared", house: "Viktor & Rolf", rating: 4.3, emoji: "⋊", notes: "Tomato · Chili · Amber" },
  { name: "Wanted", house: "Azzaro", rating: 4.2, emoji: "⋋", notes: "Lemon · Cardamom · Vetiver" },
  { name: "Chrome", house: "Azzaro", rating: 4.1, emoji: "⋌", notes: "Anise · Rosewood · Oakmoss" },
  { name: "Polo Black", house: "Ralph Lauren", rating: 4.2, emoji: "⋍", notes: "Mango · Wormwood · Patchouli" },
  { name: "Polo Blue", house: "Ralph Lauren", rating: 4.1, emoji: "⋎", notes: "Melon · Cucumber · Suede" },
  { name: "Polo Red", house: "Ralph Lauren", rating: 4.1, emoji: "⋏", notes: "Grapefruit · Saffron · Cedarwood" },
  { name: "Eternity", house: "Calvin Klein", rating: 4.1, emoji: "∞", notes: "Freesia · Sage · Sandalwood" },
  { name: "Obsession", house: "Calvin Klein", rating: 4.0, emoji: "⊛", notes: "Mandarin · Spices · Musk" },
  { name: "CK One", house: "Calvin Klein", rating: 4.2, emoji: "①", notes: "Bergamot · Green Tea · Musk" },
  { name: "Euphoria", house: "Calvin Klein", rating: 4.2, emoji: "⊜", notes: "Pomegranate · Black Orchid · Amber" },
  { name: "Davidoff Cool Water", house: "Davidoff", rating: 4.1, emoji: "≈", notes: "Mint · Lavender · Oakmoss" },
  { name: "Zino", house: "Davidoff", rating: 4.0, emoji: "≉", notes: "Lavender · Cedarwood · Musk" },
  { name: "Drakkar Noir", house: "Guy Laroche", rating: 4.0, emoji: "≊", notes: "Lavender · Rosemary · Leather" },
  { name: "Fahrenheit", house: "Dior", rating: 4.3, emoji: "°", notes: "Violet · Leather · Amber" },
  { name: "Dior Homme", house: "Dior", rating: 4.4, emoji: "⌖", notes: "Iris · Lavender · Vetiver" },
  { name: "Dior Homme Intense", house: "Dior", rating: 4.5, emoji: "⌗", notes: "Iris · Ambrette · Pear" },
  { name: "Hypnotic Poison", house: "Dior", rating: 4.3, emoji: "☠", notes: "Almond · Jasmine · Vanilla" },
  { name: "Pure Poison", house: "Dior", rating: 4.2, emoji: "⌘", notes: "Orange Blossom · Jasmine · White Musk" },
  { name: "Poison Girl", house: "Dior", rating: 4.2, emoji: "⌙", notes: "Neroli · Rose · Vanilla" },
  { name: "Chloé EDP", house: "Chloé", rating: 4.3, emoji: "⌚", notes: "Peony · Rose · Cedarwood" },
  { name: "Love Story", house: "Chloé", rating: 4.1, emoji: "⌛", notes: "Neroli · Jasmine · Cedarwood" },
  { name: "Nomade", house: "Chloé", rating: 4.2, emoji: "⌜", notes: "Freesia · Oakmoss · Amber" },
  { name: "Roses de Chloé", house: "Chloé", rating: 4.1, emoji: "⌝", notes: "Rose · Bergamot · White Musk" },
  { name: "Acqua di Parma Colonia", house: "Acqua di Parma", rating: 4.5, emoji: "⌞", notes: "Citrus · Lavender · Sandalwood" },
  { name: "Iris Nobile", house: "Acqua di Parma", rating: 4.4, emoji: "⌟", notes: "Iris · Orange Blossom · Musk" },
  { name: "Magnolia Nobile", house: "Acqua di Parma", rating: 4.3, emoji: "⌠", notes: "Magnolia · Peach · Amber" },
  { name: "Wood & Spice", house: "Acqua di Parma", rating: 4.3, emoji: "⌡", notes: "Oud · Pepper · Cedarwood" },
  { name: "Santal 33", house: "Le Labo", rating: 4.7, emoji: "⍀", notes: "Sandalwood · Cardamom · Violet" },
  { name: "Rose 31", house: "Le Labo", rating: 4.5, emoji: "⍁", notes: "Rose · Cumin · Vetiver" },
  { name: "Another 13", house: "Le Labo", rating: 4.6, emoji: "⍂", notes: "Ambrette · Moss · Musk" },
  { name: "Bergamote 22", house: "Le Labo", rating: 4.4, emoji: "⍃", notes: "Bergamot · Grapefruit · Musk" },
  { name: "Thé Noir 29", house: "Le Labo", rating: 4.5, emoji: "⍄", notes: "Black Tea · Fig · Vetiver" },
  { name: "Noir de Noir", house: "Tom Ford", rating: 4.6, emoji: "⍅", notes: "Rose · Oud · Black Truffle" },
  { name: "Rose Prick", house: "Tom Ford", rating: 4.5, emoji: "⍆", notes: "Rose · Turkish Rose · Spices" },
  { name: "Velvet Orchid", house: "Tom Ford", rating: 4.4, emoji: "⍇", notes: "Rum · Black Orchid · Suede" },
  { name: "Neroli Portofino", house: "Tom Ford", rating: 4.5, emoji: "⍈", notes: "Neroli · Citrus · Amber" },
  { name: "Soleil Blanc", house: "Tom Ford", rating: 4.4, emoji: "⍉", notes: "Ylang · Coconut · Amber" },
  { name: "Lost Cherry", house: "Tom Ford", rating: 4.6, emoji: "⍊", notes: "Cherry · Turkish Rose · Almond" },
  { name: "Fucking Fabulous", house: "Tom Ford", rating: 4.5, emoji: "⍋", notes: "Leather · Orris · Clary Sage" },
  { name: "Tuscan Leather", house: "Tom Ford", rating: 4.6, emoji: "⍌", notes: "Raspberry · Thyme · Leather" },
  { name: "Bitter Peach", house: "Tom Ford", rating: 4.5, emoji: "⍍", notes: "Peach · Cognac · Labdanum" },
  { name: "Mandarino di Amalfi", house: "Tom Ford", rating: 4.4, emoji: "⍎", notes: "Mandarin · Basil · Amber" },
  { name: "Patchouli Absolu", house: "Tom Ford", rating: 4.3, emoji: "⍏", notes: "Patchouli · Sandalwood · Amber" },
  { name: "Fougère Platine", house: "Tom Ford", rating: 4.3, emoji: "⍐", notes: "Lavender · Geranium · Coumarin" },
  { name: "Seve Exquise", house: "Annick Goutal", rating: 4.2, emoji: "⍑", notes: "Iris · Maple · Vanilla" },
  { name: "Un Matin d'Orage", house: "Annick Goutal", rating: 4.1, emoji: "⍒", notes: "Magnolia · Peony · Musk" },
  { name: "Petite Chérie", house: "Annick Goutal", rating: 4.2, emoji: "⍓", notes: "Peach · Rose · Musk" },
  { name: "Encens Flamboyant", house: "Annick Goutal", rating: 4.3, emoji: "⍔", notes: "Incense · Mastic · Cistus" },
  { name: "Mémorables", house: "Annick Goutal", rating: 4.1, emoji: "⍕", notes: "Violet · Iris · Sandalwood" },
  { name: "Arabie", house: "Serge Lutens", rating: 4.5, emoji: "⍖", notes: "Dates · Cumin · Amber" },
  { name: "Feminité du Bois", house: "Serge Lutens", rating: 4.4, emoji: "⍗", notes: "Cedar · Plum · Peach" },
  { name: "Chergui", house: "Serge Lutens", rating: 4.5, emoji: "⍘", notes: "Tobacco · Honey · Iris" },
  { name: "Sarrasins", house: "Serge Lutens", rating: 4.3, emoji: "⍙", notes: "Jasmine · Indole · Musk" },
  { name: "Ambre Sultan", house: "Serge Lutens", rating: 4.4, emoji: "⍚", notes: "Amber · Oregano · Coriander" },
  { name: "Tubéreuse Criminelle", house: "Serge Lutens", rating: 4.4, emoji: "⍛", notes: "Tuberose · Camphor · Vanilla" },
  { name: "Five O'Clock au Gingembre", house: "Serge Lutens", rating: 4.3, emoji: "⍜", notes: "Ginger · Tea · Amber" },
  { name: "Jeux de Peau", house: "Serge Lutens", rating: 4.2, emoji: "⍝", notes: "Milk · Bread · Sandalwood" },
  { name: "Diaghilev", house: "Roja Parfums", rating: 4.7, emoji: "⍞", notes: "Rose · Jasmine · Orris" },
  { name: "Enigma", house: "Roja Parfums", rating: 4.6, emoji: "⍟", notes: "Bergamot · Clary Sage · Amber" },
  { name: "Scandal", house: "Roja Parfums", rating: 4.5, emoji: "⍠", notes: "Blackcurrant · Rose · Leather" },
  { name: "Elysium", house: "Roja Parfums", rating: 4.5, emoji: "⍡", notes: "Grapefruit · Lavender · Musk" },
  { name: "Amber Oud Gold", house: "Al Haramain", rating: 4.5, emoji: "⍢", notes: "Oud · Amber · Rose" },
  { name: "Dehnal Oud Cambodi", house: "Al Haramain", rating: 4.6, emoji: "⍣", notes: "Pure Oud · Smoke · Wood" },
  { name: "L'Aventure", house: "Al Haramain", rating: 4.3, emoji: "⍤", notes: "Citrus · Leather · Amber" },
  { name: "Madinah", house: "Al Haramain", rating: 4.4, emoji: "⍥", notes: "Rose · Oud · Musk" },
  { name: "Rose Oud", house: "Ajmal", rating: 4.3, emoji: "⍦", notes: "Rose · Oud · Sandalwood" },
  { name: "Evoke Gold", house: "Ajmal", rating: 4.2, emoji: "⍧", notes: "Bergamot · Amber · Musk" },
  { name: "Aurum", house: "Ajmal", rating: 4.3, emoji: "⍨", notes: "Lemon · Neroli · Amber" },
  { name: "Wisal Dhahab", house: "Ajmal", rating: 4.4, emoji: "⍩", notes: "Saffron · Rose · Oud" },
  { name: "Oud 36", house: "Lattafa", rating: 4.4, emoji: "⍪", notes: "Oud · Sandalwood · Amber" },
  { name: "Asad", house: "Lattafa", rating: 4.3, emoji: "⍫", notes: "Leather · Vetiver · Musk" },
  { name: "Raghba", house: "Lattafa", rating: 4.4, emoji: "⍬", notes: "Vanilla · Coconut · Oud" },
  { name: "Yara", house: "Lattafa", rating: 4.3, emoji: "⍭", notes: "Fruity · Jasmine · Musk" },
  { name: "Ana Abiyedh Rouge", house: "Lattafa", rating: 4.2, emoji: "⍮", notes: "Strawberry · Rose · Musk" },
  { name: "Khamrah", house: "Lattafa", rating: 4.5, emoji: "⍯", notes: "Oud · Vanilla · Spices" },
  { name: "Badee Al Oud", house: "Lattafa", rating: 4.3, emoji: "⍰", notes: "Oud · Rose · Amber" },
  { name: "Opium", house: "Yves Saint Laurent", rating: 4.3, emoji: "⍱", notes: "Mandarin · Rose · Patchouli" },
  { name: "Nu", house: "Yves Saint Laurent", rating: 4.1, emoji: "⍲", notes: "Violet · Peach · Sandalwood" },
  { name: "Cinema", house: "Yves Saint Laurent", rating: 4.2, emoji: "⍳", notes: "Orange · Rose · Amber" },
  { name: "Elle", house: "Yves Saint Laurent", rating: 4.1, emoji: "⍴", notes: "Peony · Rose · Patchouli" },
  { name: "Parisienne", house: "Yves Saint Laurent", rating: 4.1, emoji: "⍵", notes: "Rose · Blackcurrant · Vanilla" },
  { name: "Rose Ikebana", house: "Hermès", rating: 4.4, emoji: "⍶", notes: "Rose · Rhubarb · Musk" },
  { name: "Terre d'Hermès", house: "Hermès", rating: 4.6, emoji: "⍷", notes: "Orange · Vetiver · Flint" },
  { name: "Eau des Merveilles", house: "Hermès", rating: 4.4, emoji: "⍸", notes: "Orange · Elemi · Amber" },
  { name: "Un Jardin sur le Nil", house: "Hermès", rating: 4.3, emoji: "⍹", notes: "Green Mango · Lotus · Grapefruit" },
  { name: "Jour d'Hermès", house: "Hermès", rating: 4.3, emoji: "⍺", notes: "Gardenia · Musk · Rose" },
  { name: "Twilly d'Hermès", house: "Hermès", rating: 4.3, emoji: "⍻", notes: "Ginger · Tuberose · Sandalwood" },
  { name: "H24", house: "Hermès", rating: 4.4, emoji: "⍼", notes: "Sage · Narcissus · Cedarwood" },
  { name: "Voyage d'Hermès", house: "Hermès", rating: 4.5, emoji: "⍽", notes: "Citrus · Vetiver · Amber" },
  { name: "Galop d'Hermès", house: "Hermès", rating: 4.3, emoji: "⍾", notes: "Rose · Leather · Patchouli" },
  { name: "Ambre Narguilé", house: "Hermès", rating: 4.4, emoji: "⍿", notes: "Rum · Amber · Tobacco" },
  { name: "Épice Marine", house: "Hermès", rating: 4.2, emoji: "␀", notes: "Sea · Pepper · Cedar" },
  { name: "Amber Absolute", house: "Tom Ford", rating: 4.4, emoji: "␁", notes: "Frankincense · Amber · Labdanum" },
  { name: "Shanghai Lily", house: "Tom Ford", rating: 4.3, emoji: "␂", notes: "Lily · Sandalwood · Musk" },
  { name: "Jonquille de Nuit", house: "Tom Ford", rating: 4.3, emoji: "␃", notes: "Jonquil · Honey · Musk" },
  { name: "Plum Japonais", house: "Tom Ford", rating: 4.3, emoji: "␄", notes: "Plum · Saffron · Oud" },
  { name: "Ombre Leather", house: "Tom Ford", rating: 4.5, emoji: "␅", notes: "Leather · Floral · Patchouli" },
  { name: "Vanilla Sex", house: "Tom Ford", rating: 4.4, emoji: "␆", notes: "Vanilla · Musk · Labdanum" },
  { name: "Beau de Jour", house: "Tom Ford", rating: 4.4, emoji: "␇", notes: "Lavender · Thyme · Oakmoss" },
  { name: "Grey Vetiver", house: "Tom Ford", rating: 4.4, emoji: "␈", notes: "Vetiver · Sage · Orange" },
  { name: "Noir Anthracite", house: "Tom Ford", rating: 4.3, emoji: "␉", notes: "Cypriol · Incense · Vetiver" },
  { name: "Costa Azzurra", house: "Tom Ford", rating: 4.4, emoji: "␊", notes: "Sea Notes · Cypress · Amber" },
  { name: "Champaca Absolute", house: "Tom Ford", rating: 4.3, emoji: "␋", notes: "Champaca · Tea · Amber" },
  { name: "White Suede", house: "Tom Ford", rating: 4.4, emoji: "␌", notes: "Rose · Suede · Musk" },
  { name: "Metallique", house: "Tom Ford", rating: 4.2, emoji: "␍", notes: "Metal · Iris · Musk" },
  { name: "Café Rose", house: "Tom Ford", rating: 4.3, emoji: "␎", notes: "Coffee · Rose · Amber" },
  { name: "Orchid Soleil", house: "Tom Ford", rating: 4.3, emoji: "␏", notes: "Black Orchid · Vetiver · Amber" },
  { name: "Oud Minerale", house: "Tom Ford", rating: 4.4, emoji: "␐", notes: "Marine · Oud · Amber" },
  { name: "Eau de Soleil Blanc", house: "Tom Ford", rating: 4.3, emoji: "␑", notes: "Bergamot · Ylang · Musk" },
  { name: "Fleur de Portofino", house: "Tom Ford", rating: 4.3, emoji: "␒", notes: "Citrus · Neroli · Musk" },
  { name: "Vert Bohème", house: "Tom Ford", rating: 4.2, emoji: "␓", notes: "Tomato Leaf · Vetiver · Amber" },
  { name: "Fougère d'Argent", house: "Tom Ford", rating: 4.3, emoji: "␔", notes: "Lavender · Coumarin · Musk" },
  { name: "Sole di Positano", house: "Tom Ford", rating: 4.3, emoji: "␕", notes: "Lemon · Basil · Amber" },
  { name: "Bois Marocain", house: "Tom Ford", rating: 4.3, emoji: "␖", notes: "Cedar · Vetiver · Amber" },
  { name: "Amber Absolute", house: "Tom Ford", rating: 4.4, emoji: "␗", notes: "Frankincense · Amber · Musk" },
  { name: "Oud Fleur", house: "Tom Ford", rating: 4.4, emoji: "␘", notes: "Oud · Rose · Saffron" },
  { name: "Arabian Wood", house: "Tom Ford", rating: 4.3, emoji: "␙", notes: "Oud · Cedarwood · Amber" },
  { name: "Lavender Extreme", house: "Tom Ford", rating: 4.3, emoji: "␚", notes: "Lavender · Tonka · Amber" },
  { name: "Italian Cypress", house: "Tom Ford", rating: 4.2, emoji: "␛", notes: "Cypress · Citrus · Vetiver" },
  { name: "Kyoto", house: "Tom Ford", rating: 4.3, emoji: "␜", notes: "Hinoki · Incense · Amber" },
  { name: "Shanghai Lily", house: "Tom Ford", rating: 4.2, emoji: "␝", notes: "Lily · Jasmine · Musk" },
  { name: "Japon Noir", house: "Tom Ford", rating: 4.3, emoji: "␞", notes: "Incense · Oud · Amber" },
  { name: "Santal Blush", house: "Tom Ford", rating: 4.4, emoji: "␟", notes: "Sandalwood · Rose · Amber" },
  { name: "Electric Cherry", house: "Tom Ford", rating: 4.3, emoji: "␠", notes: "Cherry · Rose · Patchouli" },
  { name: "Myrrhe Mystère", house: "Tom Ford", rating: 4.3, emoji: "␡", notes: "Myrrh · Amber · Vanilla" },
  { name: "Musc Bavarian", house: "Tom Ford", rating: 4.2, emoji: "Ω", notes: "Musk · Amber · Vetiver" },
  { name: "Eau de Parfum Intense", house: "Dior", rating: 4.4, emoji: "α", notes: "Rose · Oud · Amber" },
  { name: "Poison", house: "Dior", rating: 4.2, emoji: "β", notes: "Opoponax · Cinnamon · Honey" },
  { name: "Escale à Portofino", house: "Dior", rating: 4.2, emoji: "γ", notes: "Lemon · Basil · Neroli" },
  { name: "New Look 1947", house: "Dior", rating: 4.3, emoji: "δ", notes: "Iris · Rose · Musk" },
  { name: "Granville", house: "Dior", rating: 4.2, emoji: "ε", notes: "Petitgrain · Lily · Musk" },
  { name: "Lucky", house: "Dior", rating: 4.1, emoji: "ζ", notes: "Lychee · Rose · Amber" },
  { name: "Addict 2", house: "Dior", rating: 4.1, emoji: "η", notes: "Grapefruit · White Tea · Musk" },
  { name: "Dolce Vita", house: "Dior", rating: 4.2, emoji: "θ", notes: "Peach · Cinnamon · Vanilla" },
  { name: "Dune", house: "Dior", rating: 4.2, emoji: "ι", notes: "Aldehydes · Peony · Amber" },
];